# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d482566293fc6c027a60ad3c0297ca48bb4785373ae3396f4e40a736ef84e06d1686f70c6b0a9a93bb167f30b81451f0b4d7e6e0d7c5deb1f09d702cff45fb29

test:
  secret_key_base: ba5239ca9c2fd8a7c13d361243956571d2f8693f5a0116fb8cd9e94e1c489898bd7bd5d5091c4e2c14b471735a69978b79014360eebd8999747910cca230f9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
